<a href="https://colab.research.google.com/github/Nameless8243/TensorFlow_DL/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:

 * Introduction to tensors
 * Getting information from tensors
 * Manipulating tensors
 * Tensors & NumPy
 * Using @tf.function (a way to speed up your regular Python functions)
 * Using  GPUs with TensorFlow (or TPUs)
 * Exercises to try for yourself!



## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8., 9.]], dtype=tf.float16) #specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions of another_matrix?

another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind, speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


### Creating tensors with `tf.Variable`

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign?
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors
Random tensors are tensors of some abitrary(tetszőleges) size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
### Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1, 2],
                       [3, 4],
                       [5, 6]])
tensor1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(11)
tf.random.shuffle(tensor1, seed=11)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tensor2 = tf.constant([[7, 8],
                       [9, 10],
                       [11, 12]])

tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 10],
       [ 7,  8],
       [11, 12]], dtype=int32)>

In [ ]:
tf.random.set_seed(22)
tf.random.shuffle(tensor2, seed=22)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>

In [ ]:
tensor3 = tf.constant([[13, 14],
                       [15, 16],
                       [17, 18]])

tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 14],
       [15, 16],
       [17, 18]], dtype=int32)>

In [ ]:
tf.random.set_seed(33)
tf.random.shuffle(tensor3, seed=33)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[17, 18],
       [15, 16],
       [13, 14]], dtype=int32)>

In [ ]:
tensor4 = tf.constant([[19, 20],
                       [21, 22],
                       [23, 24]])

tensor4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 20],
       [21, 22],
       [23, 24]], dtype=int32)>

In [ ]:
tf.random.set_seed(44)
tf.random.shuffle(tensor4, seed=44)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 20],
       [23, 24],
       [21, 22]], dtype=int32)>

In [ ]:
tensor5 = tf.constant([[25, 26],
                       [27, 28],
                       [29, 30]])

tensor5

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 26],
       [27, 28],
       [29, 30]], dtype=int32)>

In [ ]:
tf.random.set_seed(55) # global level random seed
tf.random.shuffle(tensor5, seed=55) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[29, 30],
       [25, 26],
       [27, 28]], dtype=int32)>

If we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).


In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix)  # capital for matrix or tensor
# y = tf.constant(vector)  # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimensions
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions rank:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions rank: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction if you want
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too (faster)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplycation is one of the most common operations.

There are 2 rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2)
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** The dot product **

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y(requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)),  "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go througd the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
# Create a vector
E = tf.random.uniform(shape=[50], minval=0, maxval=100, dtype=tf.int32)
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 8, 20, 84, 48, 13, 21, 37, 11,  8, 66,  6, 72,  2, 96, 46, 81, 45,
       48, 66, 50, 75, 16, 39, 77, 21, 60, 28, 30, 19, 98, 76, 84, 21,  4,
       95, 24, 98, 88, 26, 93, 53, 47, 62,  4, 71, 24, 53, 17, 92, 66],
      dtype=int32)>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Get the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# Get the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [ ]:
# Get the mean of a tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

#### Standard deviation and variance are both measures of the spread or dispersion of a dataset, but they represent it in slightly different ways:

    Variance:
        The variance is the average of the squared differences from the mean of the data.
        It is calculated by taking the average of the squared differences between each data point and the mean.
        Because it involves squaring the differences, the variance gives higher weight to values that are further from the mean.
        The variance is denoted by the symbol σ^2 (sigma squared).

    Standard Deviation:
        The standard deviation is the square root of the variance.
        It measures the average distance of each data point from the mean.
        Unlike the variance, the standard deviation is in the same unit as the original data, making it easier to interpret.
        The standard deviation is denoted by the symbol σ (sigma).

In summary, while the variance gives an idea of how spread out the data is, the standard deviation provides a more interpretable measure of the same spread because it's expressed in the same units as the original data.

In [ ]:
# Get the sum of a vector
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2389>

In [ ]:
# Get the variance (for general calculations)
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))


<tf.Tensor: shape=(), dtype=float16, numpy=909.5>

In [ ]:
# Get the variance (for probabilistic calculations)
import tensorflow_probability as tfp
tfp.stats.variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=909.5>

In [ ]:
# Get the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=30.16>

## Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

* The result of tf.argmax() is typically used when you need to know the index of the maximum value in a tensor.
* The result of tf.reduce_max() is typically used when you need the actual maximum value(s) from the tensor.

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[30])
G

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [ ]:
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [ ]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [ ]:
G[15]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [ ]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [ ]:
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Create a list of indices (indices = plural of index)
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# one-hot encode our List of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="apple", off_value="banana")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'apple', b'banana', b'banana', b'banana'],
       [b'banana', b'apple', b'banana', b'banana'],
       [b'banana', b'banana', b'apple', b'banana'],
       [b'banana', b'banana', b'banana', b'apple']], dtype=object)>

the 'b' does not change the functionality of the tensor; it's just a representation detail indicating byte literals. The strings themselves are 'apple', 'banana', etc.

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Find the power of
tf.pow(H, 4)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)>

In [ ]:
tf.math.pow(H, 4)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)>

In [ ]:
# Find the element-wise exponential of H
tf.math.exp(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
       1.4841316e+02, 4.0342877e+02, 1.0966332e+03, 2.9809580e+03,
       8.1030840e+03], dtype=float32)>

In [ ]:
# Find the sine of H
tf.math.sin(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([ 0.84147096,  0.9092974 ,  0.14112   , -0.7568025 , -0.9589243 ,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.4121185 ], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
import numpy as np

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [ ]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
vector = tf.constant([3, 4])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
matrix = tf.constant([[3, 4],
                     [5, 6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# 2. Find the shape, rank and size of the tensors you created in 1.
print(f"Vector shape: {vector.shape}\n\n"
      f"Scalar shape: {scalar.shape}\n\n"
      f"Matrix shape: {matrix.shape}\n\n"
      f"Tensor shape: {tensor.shape}")

Vector shape: (2,)

Scalar shape: ()

Matrix shape: (2, 2)

Tensor shape: (3, 2, 3)


In [ ]:
print(f"Vector rank: {tf.rank(vector)}\n\n"
      f"Scalar rank: {tf.rank(scalar)}\n\n"
      f"Matrix rank: {tf.rank(matrix)}\n\n"
      f"Tensor rank: {tf.rank(tensor)}")

Vector rank: 1

Scalar rank: 0

Matrix rank: 2

Tensor rank: 3


In [ ]:
print(f"Vector size: {tf.size(vector)}\n\n"
      f"Scalar size: {tf.size(scalar)}\n\n"
      f"Matrix size: {tf.size(matrix)}\n\n"
      f"Tensor size: {tf.size(tensor)}")

Vector size: 2

Scalar size: 1

Matrix size: 4

Tensor size: 18


In [ ]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
random_tensor1 = tf.random.uniform(shape=[5, 300], seed=42)
random_tensor2 = tf.random.uniform(shape=[5, 300], seed=43)
random_tensor1, random_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68199456, 0.42772686, 0.91583705, ..., 0.7759527 , 0.23281741,
         0.44756937],
        [0.8417139 , 0.9600885 , 0.45484674, ..., 0.27437472, 0.11039436,
         0.34174395],
        [0.75364614, 0.5741807 , 0.5281739 , ..., 0.17360818, 0.9134972 ,
         0.16209841],
        [0.0090369 , 0.23039317, 0.8060751 , ..., 0.11280978, 0.0865643 ,
         0.35216224],
        [0.06173015, 0.5260377 , 0.5921991 , ..., 0.34130323, 0.00487649,
         0.19443905]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.15199935, 0.5515324 , 0.49704242, ..., 0.27851176, 0.06518638,
         0.6590928 ],
        [0.57343435, 0.41055846, 0.48867476, ..., 0.07363367, 0.13872588,
         0.73916566],
        [0.47179306, 0.77704906, 0.10686707, ..., 0.11792111, 0.05241907,
         0.44199038],
        [0.5980997 , 0.09270048, 0.21866083, ..., 0.52040863, 0.84768   ,
         0.49068427],
        [0.36618

In [ ]:
# 4. Multiply the two tensors you created in #3 using matrix multiplication.
random_tensor2T = tf.transpose(random_tensor2)
tf.matmul(random_tensor1, random_tensor2T)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.69604 , 78.47806 , 77.71608 , 80.31393 , 72.58696 ],
       [81.6739  , 78.938705, 81.39644 , 81.02225 , 72.73315 ],
       [75.65102 , 73.77399 , 73.7224  , 80.04654 , 68.73307 ],
       [85.08348 , 81.04671 , 85.098724, 85.73088 , 76.398056],
       [71.69407 , 72.143005, 74.300995, 75.774345, 66.87716 ]],
      dtype=float32)>

In [ ]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(random_tensor1, random_tensor2T, axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.69604 , 78.47806 , 77.71608 , 80.31393 , 72.58696 ],
       [81.6739  , 78.938705, 81.39644 , 81.02225 , 72.73315 ],
       [75.65102 , 73.77399 , 73.7224  , 80.04654 , 68.73307 ],
       [85.08348 , 81.04671 , 85.098724, 85.73088 , 76.398056],
       [71.69407 , 72.143005, 74.300995, 75.774345, 66.87716 ]],
      dtype=float32)>

In [7]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor6 = tf.random.uniform(shape=([224, 224, 3]), seed=44)
tensor6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.3420055 , 0.9138253 , 0.98868954],
        [0.31657588, 0.34402096, 0.64491105],
        [0.46890926, 0.62241435, 0.8380735 ],
        ...,
        [0.23947775, 0.89989316, 0.6501105 ],
        [0.32492697, 0.29383492, 0.29964685],
        [0.9002441 , 0.3302387 , 0.7886456 ]],

       [[0.39132547, 0.9433751 , 0.8350029 ],
        [0.0678637 , 0.5063102 , 0.77834606],
        [0.21263373, 0.63810647, 0.5659189 ],
        ...,
        [0.64508235, 0.5784466 , 0.7833476 ],
        [0.8612926 , 0.8368716 , 0.8873552 ],
        [0.3351984 , 0.3584689 , 0.6656232 ]],

       [[0.17287898, 0.03203976, 0.5338819 ],
        [0.93709505, 0.8846803 , 0.877216  ],
        [0.89101577, 0.52051866, 0.86556697],
        ...,
        [0.28869915, 0.7420533 , 0.5741637 ],
        [0.40021133, 0.5421115 , 0.05365705],
        [0.82813084, 0.91176414, 0.6729531 ]],

       ...,

       [[0.20260835, 0.17327166, 0.29231286],
        [0.96

In [12]:
# 7. Find the min and max values of the tensor you created in #6 along the first axis.
tf.reduce_max(tensor6, axis=1)


<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9891285 , 0.9939729 , 0.9987885 ],
       [0.9822507 , 0.9972985 , 0.9996587 ],
       [0.98958933, 0.9866961 , 0.99995947],
       [0.998765  , 0.9973836 , 0.9993894 ],
       [0.99790084, 0.9946852 , 0.99205685],
       [0.999315  , 0.9930382 , 0.99900615],
       [0.9979836 , 0.9992323 , 0.99927735],
       [0.99996924, 0.9950223 , 0.9985267 ],
       [0.9996388 , 0.9877988 , 0.99768245],
       [0.9920796 , 0.99848187, 0.9962187 ],
       [0.9889369 , 0.99429727, 0.9984462 ],
       [0.99676657, 0.9986018 , 0.9998255 ],
       [0.9942337 , 0.999357  , 0.999799  ],
       [0.99636364, 0.99521947, 0.9956261 ],
       [0.994372  , 0.9873495 , 0.99392855],
       [0.9923495 , 0.9994081 , 0.9951471 ],
       [0.97816706, 0.9991965 , 0.996259  ],
       [0.9986925 , 0.98652315, 0.99878526],
       [0.9830438 , 0.99554276, 0.9994526 ],
       [0.99593294, 0.99912274, 0.990832  ],
       [0.99582255, 0.9993372 , 0.9953331 ],
     

In [13]:
tf.reduce_min(tensor6, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[6.29377365e-03, 2.45487690e-03, 6.20365143e-04],
       [8.57114792e-04, 1.56915188e-03, 1.16403103e-02],
       [5.01215458e-03, 7.77709484e-03, 5.41090965e-03],
       [9.22560692e-04, 4.24861908e-04, 1.54423714e-03],
       [4.23860550e-03, 6.26111031e-03, 3.56280804e-03],
       [2.01058388e-03, 1.81019306e-03, 5.16915321e-03],
       [1.20246410e-03, 4.82356548e-03, 7.01677799e-03],
       [2.50601768e-03, 8.69750977e-04, 1.22678280e-03],
       [6.71184063e-03, 5.35750389e-03, 3.73482704e-04],
       [1.45024061e-02, 5.23090363e-04, 7.84420967e-03],
       [2.97093391e-03, 3.24976444e-03, 1.57415867e-03],
       [1.14989281e-03, 2.26020813e-03, 7.55429268e-03],
       [3.66353989e-03, 3.04508209e-03, 4.02307510e-03],
       [5.72395325e-03, 4.52208519e-03, 1.74689293e-03],
       [1.18446350e-03, 3.20219994e-03, 3.88872623e-03],
       [3.64542007e-04, 8.30543041e-03, 1.32800341e-02],
       [7.25269318e-04, 4.32479382e-03

In [20]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor8 = tf.random.normal([1, 224, 224, 3])

In [21]:
tf.reshape(tensor8, [224, 224, 3])

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.1230983 , -0.22385171, -0.6025215 ],
        [-0.22605087, -0.818451  , -1.0302287 ],
        [ 1.116765  ,  0.05814207,  0.5278414 ],
        ...,
        [-1.0446559 ,  0.14326282,  0.56483465],
        [ 0.5765057 , -0.16163316,  0.32420754],
        [-0.8854247 , -0.14323793, -0.12337816]],

       [[ 0.3107016 ,  0.6794291 ,  0.9546586 ],
        [-0.02231018, -0.5854938 , -1.7510735 ],
        [-0.7536757 , -0.68509024, -1.5201691 ],
        ...,
        [-1.8132005 , -0.70938885,  0.514351  ],
        [ 0.67457795,  0.5352632 ,  0.6604773 ],
        [ 0.32409763, -0.13752128, -0.6247216 ]],

       [[-1.3004781 ,  0.49440563, -1.2841603 ],
        [-0.14152785, -0.7307738 ,  0.08226755],
        [-1.1267945 ,  0.0660411 ,  1.4737654 ],
        ...,
        [ 0.14651985, -0.3430131 ,  0.99038637],
        [-0.27855992,  1.3063089 ,  0.8358227 ],
        [ 0.6582148 ,  1.861302  ,  0.60377145]],

       ...,

     

In [ ]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.